version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro #same as before
      - /opt/docker/volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d # to update vhost configuration
      - /opt/docker/volumes/nginx-proxy/html:/usr/share/nginx/html # to write challenge files
      - /opt/docker/volumes/nginx-proxy/certs:/etc/nginx/certs:ro